# Generated by Django 5.2 on 2025-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("server", models.CharField(max_length=100)),
                (
                    "target_profit_usd",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=10),
                ),
                (
                    "risk_percent",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("symbols", models.JSONField(default=list)),
                ("max_trades_per_symbol", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
